{% set name = "pfzy" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kazhala/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4a36126e045da6471c53e9ea36424296307a1841bd828a41574d7a4aa58dbcea

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python

test:
  imports:
    - pfzy
  requires:
    - pip
    - pytest
    - pytest-asyncio
  source_files:
    - tests
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://github.com/kazhala/pfzy
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Python port of the fzy fuzzy string matching algorithm.
  description: |
    Python port of the fzy fuzzy string matching algorithm.
  doc_url: https://pfzy.readthedocs.io
  dev_url: https://github.com/kazhala/pfzy

extra:
  recipe-maintainers:
    - avsthiago
  skip-lints:
    - missing_wheel
